name: Run PDK tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install PDK
        run: gem install pdk

      - name: Install PDK Ruby Dependencies
        run: pdk bundle install

      - name: Validate
        run: pdk validate

      - name: Run Unit Tests
        run: pdk test unit
